"""
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


indexIterator = 0

fibNumbers = [1,2]

lastIndexNum = fibNumbers[-1]

while (lastIndexNum < 4000000):
    lastIndexNum = fibNumbers[-1]
    fibNumbers.append(fibNumbers[indexIterator] + fibNumbers[indexIterator+1])
    indexIterator += 1

sum = 0

for number in fibNumbers:
    if (number % 2 == 0):
        sum += number

print(sum)

